// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Shared.Repository.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seeddb5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seeddb5));
        
        string IMigrationMetadata.Id
        {
            get { return "201506070756196_Seed db 5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
