// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Shared.Repository.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seeddb8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seeddb8));
        
        string IMigrationMetadata.Id
        {
            get { return "201506070831148_Seed db 8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
