// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Shared.Repository.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Questionpointsfrominttodecimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Questionpointsfrominttodecimal));
        
        string IMigrationMetadata.Id
        {
            get { return "201506071117217_Question points from int to decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
